// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/8f094200664a2b10bc597016f5486066a174e098/tests/lib/rules/html-quotes.js
/**
 * @author Toru Nagashima
 * @copyright 2017 Toru Nagashima. All rights reserved.
 * See LICENSE file in root directory for full license.
 */
'use strict'

// ------------------------------------------------------------------------------
// Requirements
// ------------------------------------------------------------------------------

const RuleTester = require('eslint').RuleTester
const path = require('path')
const rule = require('../../fixtures/eslint-plugin-vue/lib/rules/html-quotes')

// ------------------------------------------------------------------------------
// Tests
// ------------------------------------------------------------------------------

const tester = new RuleTester({
  parser: require.resolve('vue-eslint-parser'),
  parserOptions: {  ecmaVersion: 2015 , templateTokenizer: { pug: path.resolve(__dirname, '../../../')}}
})

tester.run('html-quotes', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: ''
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">.foo</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:class="foo")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">.foo</template>`,
      options: ['double']
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:class="foo")</template>`,
      options: ['double']
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">.foo</template>`,
      options: ['single']
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:class='foo')</template>`,
      options: ['single']
    },
    // avoidEscape
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(attr='foo\"bar')</template>`,
      options: ['double', { avoidEscape: true }]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(attr="foo\'bar")</template>`,
      options: ['single', { avoidEscape: true }]
    },

    // Invalid EOF
    {
      code: `<!-- CONVERT ERROR -->Unexpected EOF in tag.<template><div class="foo></div></template>`,
      options: ['single']
    },
    {
      code: `<!-- CONVERT ERROR -->Unexpected EOF in tag.<template><div class='foo></div></template>`,
      options: ['double']
    }
  ],
  invalid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">.foo</template>`,
      output: `<template lang="pug">.foo</template>`,
      errors: ['Expected to be enclosed by double quotes.']
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">.foo</template>`,
      output: `<template lang="pug">.foo</template>`,
      errors: ['Expected to be enclosed by double quotes.']
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:class=foo)</template>`,
      output: `<template lang="pug">div(:class="foo")</template>`,
      errors: ['Expected to be enclosed by double quotes.']
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:class='foo')</template>`,
      output: `<template lang="pug">div(:class="foo")</template>`,
      errors: ['Expected to be enclosed by double quotes.']
    },
    {
      filename: 'test.vue',
      code: `<!-- CONVERT ERROR -->Unquoted attribute value cannot contain U+0022 ("), U+0027 ('), U+003C (<), U+003D (=), and U+0060 (\`).<template><div :class=foo+"bar"></div></template>`,
      output: `<template lang="pug">div(:class="foo+&quot;bar&quot;")</template>`,
      errors: ['Expected to be enclosed by double quotes.']
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">.foo</template>`,
      output: `<template lang="pug">.foo</template>`,
      options: ['double'],
      errors: ['Expected to be enclosed by double quotes.']
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">.foo</template>`,
      output: `<template lang="pug">.foo</template>`,
      options: ['double'],
      errors: ['Expected to be enclosed by double quotes.']
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:class=foo)</template>`,
      output: `<template lang="pug">div(:class="foo")</template>`,
      options: ['double'],
      errors: ['Expected to be enclosed by double quotes.']
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:class='foo')</template>`,
      output: `<template lang="pug">div(:class="foo")</template>`,
      options: ['double'],
      errors: ['Expected to be enclosed by double quotes.']
    },
    {
      filename: 'test.vue',
      code: `<!-- CONVERT ERROR -->Unquoted attribute value cannot contain U+0022 ("), U+0027 ('), U+003C (<), U+003D (=), and U+0060 (\`).<template><div :class=foo+"bar"></div></template>`,
      output: `<template lang="pug">div(:class="foo+&quot;bar&quot;")</template>`,
      options: ['double'],
      errors: ['Expected to be enclosed by double quotes.']
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">.foo</template>`,
      output: `<template lang="pug">.foo</template>`,
      options: ['single'],
      errors: ['Expected to be enclosed by single quotes.']
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">.foo</template>`,
      output: `<template lang="pug">.foo</template>`,
      options: ['single'],
      errors: ['Expected to be enclosed by single quotes.']
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:class=foo)</template>`,
      output: `<template lang="pug">div(:class='foo')</template>`,
      options: ['single'],
      errors: ['Expected to be enclosed by single quotes.']
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:class="foo")</template>`,
      output: `<template lang="pug">div(:class='foo')</template>`,
      options: ['single'],
      errors: ['Expected to be enclosed by single quotes.']
    },
    {
      filename: 'test.vue',
      code: `<!-- CONVERT ERROR -->Unquoted attribute value cannot contain U+0022 ("), U+0027 ('), U+003C (<), U+003D (=), and U+0060 (\`).<template><div :class=foo+'bar'></div></template>`,
      output: `<template lang="pug">div(:class='foo+&apos;bar&apos;')</template>`,
      options: ['single'],
      errors: ['Expected to be enclosed by single quotes.']
    },
    // avoidEscape
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(attr="foo")</template>`,
      output: `<template lang="pug">div(attr="foo")</template>`,
      options: ['double', { avoidEscape: true }],
      errors: ['Expected to be enclosed by double quotes.']
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(attr="bar")</template>`,
      output: `<template lang="pug">div(attr="bar")</template>`,
      options: ['single', { avoidEscape: true }],
      errors: ['Expected to be enclosed by single quotes.']
    },
    {
      filename: 'test.vue',
      code: `<!-- CONVERT ERROR -->Unquoted attribute value cannot contain U+0022 ("), U+0027 ('), U+003C (<), U+003D (=), and U+0060 (\`).<template><div attr=foo"bar></div></template>`,
      output: `<template lang="pug">div(attr='foo\"bar')</template>`,
      options: ['double', { avoidEscape: true }],
      errors: ['Expected to be enclosed by double quotes.']
    },
    {
      filename: 'test.vue',
      code: `<!-- CONVERT ERROR -->Unquoted attribute value cannot contain U+0022 ("), U+0027 ('), U+003C (<), U+003D (=), and U+0060 (\`).<template><div attr=foo'bar></div></template>`,
      output: `<template lang="pug">div(attr="foo\'bar")</template>`,
      options: ['single', { avoidEscape: true }],
      errors: ['Expected to be enclosed by single quotes.']
    },
    {
      filename: 'test.vue',
      code: `<!-- CONVERT ERROR -->Unquoted attribute value cannot contain U+0022 ("), U+0027 ('), U+003C (<), U+003D (=), and U+0060 (\`).<template><div attr=foo"bar\'baz></div></template>`,
      output: `<template lang="pug">div(attr='foo"bar\'baz')</template>`,
      options: ['double', { avoidEscape: true }],
      errors: ['Expected to be enclosed by double quotes.']
    },
    {
      filename: 'test.vue',
      code: `<!-- CONVERT ERROR -->Unquoted attribute value cannot contain U+0022 ("), U+0027 ('), U+003C (<), U+003D (=), and U+0060 (\`).<template><div attr=foo"bar\'baz></div></template>`,
      output: `<template lang="pug">div(attr='foo\"bar'baz')</template>`,
      options: ['single', { avoidEscape: true }],
      errors: ['Expected to be enclosed by single quotes.']
    }
  ]
})
