// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/8f094200664a2b10bc597016f5486066a174e098/tests/lib/rules/keyword-spacing.js @2022-03-19T13:08:36.624Z
/**
 * @author Yosuke Ota
 */
'use strict'

const RuleTester = require('eslint').RuleTester
const path = require('path')
const rule = require('../../fixtures/eslint-plugin-vue/lib/rules/keyword-spacing')

const tester = new RuleTester({
  parser: require.resolve('vue-eslint-parser'),
  parserOptions: {  ecmaVersion: 2015 , templateTokenizer: { pug: path.resolve(__dirname, '../../../')}}
})

tester.run('keyword-spacing', rule, {
  valid: [
    `<template lang="pug">
div(@event="
  if (foo) {
    //...
  } else if (bar) {
    //...
  } else {
    //...
  }
")
</template>`,
    {
      code: `<template lang="pug">
div(@event="
  if(foo) {
    //...
  }else if(bar) {
    //...
  }else{
    //...
  }
")
</template>`,
      options: [{ before: false, after: false }]
    },
    `<template lang="pug">div(:[(function(){return(1)})()]="val")</template>`
  ],
  invalid: [
    {
      code: `<template lang="pug">
div(@event="
  if(foo) {
    //...
  }else if(bar) {
    //...
  }else{
    //...
  }
")
</template>`,
      output: `<template lang="pug">
div(@event="
  if (foo) {
    //...
  } else if (bar) {
    //...
  } else {
    //...
  }
")
</template>`,
      errors: [
        {
          message: 'Expected space(s) after "if".',
          line: 3
        },
        {
          message: 'Expected space(s) before "else".',
          line: 5
        },
        {
          message: 'Expected space(s) after "if".',
          line: 5
        },
        {
          message: 'Expected space(s) before "else".',
          line: 7
        },
        {
          message: 'Expected space(s) after "else".',
          line: 7
        }
      ]
    },
    {
      code: `<template lang="pug">
div(@event="
  if (foo) {
    //...
  } else if (bar) {
    //...
  } else {
    //...
  }
")
</template>`,
      options: [{ before: false, after: false }],
      output: `<template lang="pug">
div(@event="
  if(foo) {
    //...
  }else if(bar) {
    //...
  }else{
    //...
  }
")
</template>`,
      errors: [
        {
          message: 'Unexpected space(s) after "if".',
          line: 3
        },
        {
          message: 'Unexpected space(s) before "else".',
          line: 5
        },
        {
          message: 'Unexpected space(s) after "if".',
          line: 5
        },
        {
          message: 'Unexpected space(s) before "else".',
          line: 7
        },
        {
          message: 'Unexpected space(s) after "else".',
          line: 7
        }
      ]
    },
    {
      code: `<template lang="pug">div(:[(function(){return(1)})()]="(function(){return(1)})()")</template>`,
      output: `<template lang="pug">div(:[(function(){return(1)})()]="(function(){return (1)})()")</template>`,
      errors: [
        {
          message: 'Expected space(s) after "return".',
          line: 2
        }
      ]
    }
  ]
})
