// SKIP AUTOGENERATION
// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/8f094200664a2b10bc597016f5486066a174e098/tests/lib/rules/quote-props.js
/**
 * @author Yosuke Ota
 * See LICENSE file in root directory for full license.
 */
'use strict'

const RuleTester = require('eslint').RuleTester
const path = require('path')
const rule = require('../../fixtures/eslint-plugin-vue/lib/rules/quote-props')

const tester = new RuleTester({
  parser: require.resolve('vue-eslint-parser'),
  parserOptions: { 
    ecmaVersion: 2020,
    sourceType: 'module'
  , templateTokenizer: { pug: path.resolve(__dirname, '../../../')}}
})

tester.run('quote-props', rule, {
  valid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:style="{'height': '100vh'}")</template>`
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(:style="{height: '100vh'}")</template>`,
      options: ['as-needed']
    }
  ],
  invalid: [
//     {
//       filename: 'test.vue',
//       code: `<!-- CONVERT ERROR -->Unquoted attribute value cannot contain U+0022 ("), U+0027 ('), U+003C (<), U+003D (=), and U+0060 (\`).
// <!-- CONVERT ERROR -->Unquoted attribute value cannot contain U+0022 ("), U+0027 ('), U+003C (<), U+003D (=), and U+0060 (\`).      <template>
//         <div :style="{height: '100vh'}"></div>
//         <div :style='{height: "100vh"}'></div>
//         <div :style={height:"100vh"}></div>
//       </template>
//       `,
//       output: `<!-- CONVERT ERROR -->Unquoted attribute value cannot contain U+0022 ("), U+0027 ('), U+003C (<), U+003D (=), and U+0060 (\`).
// <!-- CONVERT ERROR -->Unquoted attribute value cannot contain U+0022 ("), U+0027 ('), U+003C (<), U+003D (=), and U+0060 (\`).      <template>
//         <div :style="{'height': '100vh'}"></div>
//         <div :style='{"height": "100vh"}'></div>
//         <div :style={"height":"100vh"}></div>
//       </template>
//       `,
//       errors: [
//         {
//           message: "Unquoted property 'height' found.",
//           line: 3,
//           column: 23
//         },
//         {
//           message: "Unquoted property 'height' found.",
//           line: 4,
//           column: 23
//         },
//         {
//           message: "Unquoted property 'height' found.",
//           line: 5,
//           column: 22
//         }
//       ]
//     },
    {
      filename: 'test.vue',
      code: `<template lang="pug">
div(:style="{'height': '100vh'}")
div(:style='{"height": "100vh"}')
</template>`,
      output: `<template lang="pug">
div(:style="{height: '100vh'}")
div(:style='{height: "100vh"}')
</template>`,
      options: ['as-needed'],
      errors: [
        {
          message: "Unnecessarily quoted property 'height' found.",
          line: 3,
          column: 23
        },
        {
          message: "Unnecessarily quoted property 'height' found.",
          line: 4,
          column: 23
        }
      ]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">| {{ ({foo:42}).foo }}</template>`,
      output: `<template
      <template lang="pug">| {{ ({&quot;foo&quot;:42}).foo }}</template>`,
      errors: [
        {
          message: "Unquoted property 'foo' found.",
          line: 3,
          column: 14
        }
      ]
    }
  ]
})
