// AUTOGENERATED FROM https://github.com/vuejs/eslint-plugin-vue/blob/8f094200664a2b10bc597016f5486066a174e098/tests/lib/rules/valid-v-text.js @2022-03-19T14:17:43.860Z
/**
 * @author Toru Nagashima
 * @copyright 2017 Toru Nagashima. All rights reserved.
 * See LICENSE file in root directory for full license.
 */
'use strict'

// ------------------------------------------------------------------------------
// Requirements
// ------------------------------------------------------------------------------

const RuleTester = require('eslint').RuleTester
const path = require('path')
const rule = require('../../fixtures/eslint-plugin-vue/lib/rules/valid-v-text')

// ------------------------------------------------------------------------------
// Tests
// ------------------------------------------------------------------------------

const tester = new RuleTester({
  parser: require.resolve('vue-eslint-parser'),
  parserOptions: {  ecmaVersion: 2015 , templateTokenizer: { pug: path.resolve(__dirname, '../../../')}}
})

tester.run('valid-v-text', rule, {
  valid: [
    {
      filename: 'test.js',
      code: 'test'
    },
    {
      filename: 'test.vue',
      code: ''
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-text="foo")</template>`
    },
    // parsing error
    {
      filename: 'parsing-error.vue',
      code: `<template lang="pug">div(v-text=".")</template>`
    },
    // comment value (parsing error)
    {
      filename: 'parsing-error.vue',
      code: `<template lang="pug">div(v-text="/**/")</template>`
    }
  ],
  invalid: [
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-text:aaa="foo")</template>`,
      errors: ["'v-text' directives require no argument."]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-text.aaa="foo")</template>`,
      errors: ["'v-text' directives require no modifier."]
    },
    {
      filename: 'test.vue',
      code: `<template lang="pug">div(v-text)</template>`,
      errors: ["'v-text' directives require that attribute value."]
    },
    // empty value
    {
      filename: 'empty-value.vue',
      code: `<template lang="pug">div(v-text="")</template>`,
      errors: ["'v-text' directives require that attribute value."]
    }
  ]
})
